### ISSUE TITLE
能不能添加一些跨平台的下载软件？

### ISSUE THREAD

**Issue by i990049** [YemaPT-org/wiki#1]
WebTorrent Desktop v0.24.0
https://webtorrent.io/desktop/
Client
WebTorrent/0.108.6 (https://webtorrent.io)
peer id
-WD0024-xxxxxxxxxxxx
这是BT软件里面的快播，对于热种可以调用VLC边下边播，以上12个X为英文和数字的通配符，如果新架构支持正则表达，建议自动支持0.xx.x/-WD0xxx系列，免去后续升级适配，谢谢

BiglyBT 3.X版
https://github.com/BiglySoftware/BiglyBT/releases
Client
BiglyBT 3.4.0.0
peer_id=-BI3400-xxxxxxxxxxxx
Client
BiglyBT 3.6.0.0
peer_id=-BI3600-xxxxxxxxxxxx
这是azureus/vuze的开源社区版，同样是JAVA写的软件，没有ut和bc烦人的广告，以上12个X为英文和数字的通配符，如果新架构支持正则表达，建议自动支持3.x.x.x/-BI3xxx系列，免去后续升级适配，谢谢

**Comment by yamapt** [comment]
> WebTorrent Desktop v0.24.0 https://webtorrent.io/desktop/ Client WebTorrent/0.108.6 (https://webtorrent.io) peer id -WD0024-xxxxxxxxxxxx 这是BT软件里面的快播，对于热种可以调用VLC边下边播，以上12个X为英文和数字的通配符，如果新架构支持正则表达，建议自动支持0.xx.x/-WD0xxx系列，免去后续升级适配，谢谢
> 
> BiglyBT 3.X版 https://github.com/BiglySoftware/BiglyBT/releases Client BiglyBT 3.4.0.0 peer_id=-BI3400-xxxxxxxxxxxx Client BiglyBT 3.6.0.0 peer_id=-BI3600-xxxxxxxxxxxx 这是azureus/vuze的开源社区版，同样是JAVA写的软件，没有ut和bc烦人的广告，以上12个X为英文和数字的通配符，如果新架构支持正则表达，建议自动支持3.x.x.x/-BI3xxx系列，免去后续升级适配，谢谢

收到建议，会尽快适配

**Comment by yamapt** [comment]
已添加
