### ISSUE TITLE
如果站长缺资源，可以先做个自动转发脚本

### ISSUE THREAD

**Issue by i990049** [YemaPT-org/wiki#3]
引入自动下载机，第一时间转发热种，国外盒子不限速随便刷，但是基本全站HR，外站都没有新人考核，做够HR就行，建议可以做个新人强制打开站内欢迎信件的，告诉新人游戏规则，有速度的保种才有魔力，盒子和家宽都可以无限制玩耍，但是要注意HR。
https://github.com/autodl-community/autodl-trackers/tree/master/trackers
等不到其国内辅种工具适配，可以先使用使用cs辅种https://github.com/cross-seed/cross-seed?tab=readme-ov-file

**Comment by yamapt** [comment]
开发资源有限，请联系对应工具owner提issue支持。HR问题已记录，新人游戏规则提醒会尽快加上。
