### ISSUE TITLE
修改新人考核和等级晋升条件，用做种积分取代上传数据成为考核参数

### ISSUE THREAD

**Issue by i990049** [YemaPT-org/wiki#4]
野马目前没有发布组和保种组，用上传流量来考核新人是不合理的，新人发的种子没人下载怎么会有上传流量？学馒头拆包下载大包内网也没什么上传，况且现在人多地少的城市运营商到处都在查水表，某个官组死掉的站点和某个新站就有只考核新人做种积分的选项。PT的核心是保种不是刷流，外站都没考核，只有中国才有，既然其他站点的新人考核里面有做种积分，为什么不用做种积分成为晋升等级的条件？而且我没看到这个站点有搜索箱功能，搜索箱可以一键搜出全站最多下载和做种的免费种子，RSS更是不知道被藏在哪个角落了，建议学unit3d站点开通永久免费标签供RSS方便订阅。做种积分是没有各种签到勋章后宫官种加成的原始魔力，已经成为各大站点发药的参考条件。野马的时魔上限是50，按照外站filelist用时魔上限做种1年可兑换永久VIP的模式，等级晋升尽量向家宽靠拢，假设一个人除去工作学习睡觉，每天最多8个小时上限，为了计算方便，每个月最多250小时，那用50*250=12500为一个等级，一年就是15万做种积分，分成10个等级，每个等级就对应1.5万积分。
什么样的晋升条件培养出什么样的人，传统的等级晋升和魔力公式刻意强调上传数据和孤种，所以造就了刷完就跑的盒子和孤种限速的奇葩，站点管理反而需要制定更多的限速规则和花更多的精力查限速，想要做到佛系管理又不让站点出问题，就要引入全站弹性HR和有速度因素奖励的魔力公式，野马目前使用的公式并没有引入速度因素，有速度因素的公式之前已经给过建议。
https://wwi.lanzoup.com/i2ngb1xygieh
发大包可以，但是要求出种后才能产生魔力，弹性HR时间跟文件大小成正比，发种人知道有弹性HR，会自觉发相对比较小的文件，可以减少大包不出种的风险，也可以避免盲目刷流，用户想下载自己想要的视频就自觉HR，不想HR就不下载，间接减轻服务器缓存日记压力。可以像外站用盒子刷，但有弹性HR不能刷完就跑，可以给大包辅种，给孤种辅种有额外奖励，但是没有上传速度时魔就低，这样的站点才有活力，管理也不用搞什么限速规则和大包零魔，更不用逐个限速查水表。

**Comment by yamapt** [comment]
您的建议非常好，后续迭代会优先考虑您的建议。
